name: Test theme starters

on:
  push:
    branches:
      - main
    paths:
      - 'Organize/src/starters/*.pdf'
  pull_request:
    branches:
      - main
    paths:
      - 'Organize/src/starters/*.pdf'
  workflow_dispatch:

jobs:
  Init_all_themes:
    runs-on: macos-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Organize.py with all passwords
        env:
          PASSWORD_I: ${{ secrets.PASSWORD_ENCRYPTED_I }}
          PASSWORD_II: ${{ secrets.PASSWORD_ENCRYPTED_II }}
          PASSWORD_III: ${{ secrets.PASSWORD_ENCRYPTED_III }}
          PASSWORD_IV: ${{ secrets.PASSWORD_ENCRYPTED_IV }}
          PASSWORD_V: ${{ secrets.PASSWORD_ENCRYPTED_V }}
          PASSWORD_VI: ${{ secrets.PASSWORD_ENCRYPTED_VI }}
          PASSWORD_VII: ${{ secrets.PASSWORD_ENCRYPTED_VII }}
        run: |
          (
            [ -z "$PASSWORD_I" ] && printf '\n\n\n' || echo "$PASSWORD_I"
            [ -z "$PASSWORD_II" ] && printf '\n\n\n' || echo "$PASSWORD_II"
            [ -z "$PASSWORD_III" ] && printf '\n\n\n' || echo "$PASSWORD_III"
            [ -z "$PASSWORD_IV" ] && printf '\n\n\n' || echo "$PASSWORD_IV"
            [ -z "$PASSWORD_V" ] && printf '\n\n\n' || echo "$PASSWORD_V"
            [ -z "$PASSWORD_VI" ] && printf '\n\n\n' || echo "$PASSWORD_VI"
            [ -z "$PASSWORD_VII" ] && printf '\n\n\n' || echo "$PASSWORD_VII"
          ) | python3.10 Organize/Organize.py INIT

      - name: Test writing to themes
        shell: bash
        run: |
          for file in Notebooks/*.pdf; do
            echo "Przygotowuje zeszytu $file do symulacji uzywania"
            mv "$file" Notebooks/input.pdf
            python Organize/src/additional_scripts/simulate_writing.py

            # Usuwam wszystkie Rozwiązania projektu
            find ./Solutions -type f -path '*/resources/pdfs/source_raw.pdf' -exec rm -f {} \;

            # Odpalam skrypt na zeszycie
            python Organize/Organize.py raw

            # Sprawdzenie dla zadań nieparzystych: rozwiązanie musi istnieć
            find Solutions -type d -regex '.*[13579]$' | while read dir; do
                if [ ! -f "$dir/resources/pdfs/source_raw.pdf" ]; then
                    echo "Błąd: Plik source_raw.pdf nie znaleziony w folderze: $dir"
                    exit 1  # Rzuca wyjątek (kończy skrypt z kodem błędu)
                fi
            done

            # Sprawdzenie dla zadań parzystych: rozwiązanie nie powinno istnieć
            find Solutions -type d -regex '.*[02468]$' | while read dir; do
                if [ -f "$dir/resources/pdfs/source_raw.pdf" ]; then
                    echo "Błąd: Plik source_raw.pdf nie powinien być obecny w folderze: $dir"
                    exit 1  # Rzuca wyjątek (kończy skrypt z kodem błędu)
                fi
            done

            echo "Zeszyt pomyslnie przeszedł kontrole"
            rm -f Notebooks/input.pdf
            rm -f Organize/output.pdf
          done
          echo "Pomyslnie sprawdzono dzialanie kazdego zeszytu!"
